/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeAnExpertRouteImport } from './routes/become-an-expert'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as FindMyExpertRouteImport } from './routes/find-my-expert'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardExpertApplicationsRouteImport } from './routes/dashboard.expert-applications'
import { Route as DashboardExpertsListRouteImport } from './routes/dashboard.experts-list'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as ExpertsIdRouteImport } from './routes/experts.$id'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as DashboardVideoBookingRefRouteImport } from './routes/dashboard.video.$bookingRef'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnExpertRoute = BecomeAnExpertRouteImport.update({
  id: '/become-an-expert',
  path: '/become-an-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyExpertRoute = FindMyExpertRouteImport.update({
  id: '/find-my-expert',
  path: '/find-my-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpertApplicationsRoute =
  DashboardExpertApplicationsRouteImport.update({
    id: '/expert-applications',
    path: '/expert-applications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExpertsListRoute = DashboardExpertsListRouteImport.update({
  id: '/experts-list',
  path: '/experts-list',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ExpertsIdRoute = ExpertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertsRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const DashboardVideoBookingRefRoute =
  DashboardVideoBookingRefRouteImport.update({
    id: '/video/$bookingRef',
    path: '/video/$bookingRef',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-an-expert': typeof BecomeAnExpertRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/find-my-expert': typeof FindMyExpertRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/expert-applications': typeof DashboardExpertApplicationsRoute
  '/dashboard/experts-list': typeof DashboardExpertsListRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/video/$bookingRef': typeof DashboardVideoBookingRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-an-expert': typeof BecomeAnExpertRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/find-my-expert': typeof FindMyExpertRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/expert-applications': typeof DashboardExpertApplicationsRoute
  '/dashboard/experts-list': typeof DashboardExpertsListRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/video/$bookingRef': typeof DashboardVideoBookingRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-an-expert': typeof BecomeAnExpertRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/find-my-expert': typeof FindMyExpertRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/expert-applications': typeof DashboardExpertApplicationsRoute
  '/dashboard/experts-list': typeof DashboardExpertsListRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/video/$bookingRef': typeof DashboardVideoBookingRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-an-expert'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/experts'
    | '/find-my-expert'
    | '/login'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/clients'
    | '/dashboard/contacts'
    | '/dashboard/expert-applications'
    | '/dashboard/experts-list'
    | '/dashboard/integrations'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/experts/$id'
    | '/portfolio/$slug'
    | '/dashboard/'
    | '/dashboard/video/$bookingRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-an-expert'
    | '/blog'
    | '/book'
    | '/contact'
    | '/experts'
    | '/find-my-expert'
    | '/login'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/clients'
    | '/dashboard/contacts'
    | '/dashboard/expert-applications'
    | '/dashboard/experts-list'
    | '/dashboard/integrations'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/experts/$id'
    | '/portfolio/$slug'
    | '/dashboard'
    | '/dashboard/video/$bookingRef'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-an-expert'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/experts'
    | '/find-my-expert'
    | '/login'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/categories'
    | '/dashboard/clients'
    | '/dashboard/contacts'
    | '/dashboard/expert-applications'
    | '/dashboard/experts-list'
    | '/dashboard/integrations'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/experts/$id'
    | '/portfolio/$slug'
    | '/dashboard/'
    | '/dashboard/video/$bookingRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeAnExpertRoute: typeof BecomeAnExpertRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExpertsRoute: typeof ExpertsRouteWithChildren
  FindMyExpertRoute: typeof FindMyExpertRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-expert': {
      id: '/become-an-expert'
      path: '/become-an-expert'
      fullPath: '/become-an-expert'
      preLoaderRoute: typeof BecomeAnExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-expert': {
      id: '/find-my-expert'
      path: '/find-my-expert'
      fullPath: '/find-my-expert'
      preLoaderRoute: typeof FindMyExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expert-applications': {
      id: '/dashboard/expert-applications'
      path: '/expert-applications'
      fullPath: '/dashboard/expert-applications'
      preLoaderRoute: typeof DashboardExpertApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experts-list': {
      id: '/dashboard/experts-list'
      path: '/experts-list'
      fullPath: '/dashboard/experts-list'
      preLoaderRoute: typeof DashboardExpertsListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/experts/$id': {
      id: '/experts/$id'
      path: '/$id'
      fullPath: '/experts/$id'
      preLoaderRoute: typeof ExpertsIdRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/dashboard/video/$bookingRef': {
      id: '/dashboard/video/$bookingRef'
      path: '/video/$bookingRef'
      fullPath: '/dashboard/video/$bookingRef'
      preLoaderRoute: typeof DashboardVideoBookingRefRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardExpertApplicationsRoute: typeof DashboardExpertApplicationsRoute
  DashboardExpertsListRoute: typeof DashboardExpertsListRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardVideoBookingRefRoute: typeof DashboardVideoBookingRefRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardExpertApplicationsRoute: DashboardExpertApplicationsRoute,
  DashboardExpertsListRoute: DashboardExpertsListRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardVideoBookingRefRoute: DashboardVideoBookingRefRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ExpertsRouteChildren {
  ExpertsIdRoute: typeof ExpertsIdRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsIdRoute: ExpertsIdRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeAnExpertRoute: BecomeAnExpertRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExpertsRoute: ExpertsRouteWithChildren,
  FindMyExpertRoute: FindMyExpertRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
